### ISSUE TITLE
Добавить в admin_smoke хелпер override_defaults

### ISSUE THREAD

**Issue by tumb1er** [just-work/django-admin-smoke#9]
Для тех проектов, в которых внутренние настройки хранятся в defaults-файлах, экстремально полезным хелпером является декоратор/контекстный менеджер `override_defaults` (см. Django `override_settings`).
Нужно добавить его в библиотеку, заодно описав рядом с константой `second` аналогичные `minute`, `hour` и day`

**Comment by VVyacheslav** [comment]
#21830 https://redmine.just-work.org/issues/21830

**Comment by tumb1er** [comment]
Соответствующий хелпер добавлен в just-work/django-testing-utils.
